@startuml
!include <office/all>
!include <tupadr3/common>


OFF_ADMINISTRATOR(KBAdmin,"KB Admin")
OFF_ADMINISTRATOR(3rdPartyAdmin,"3rd Party Admin")

OFF_WORKSTATION_PC(KBendpoint,"KB Device")
OFF_WORKSTATION_PC(ForeignDevice,"non-KB Device")
OFF_WORKSTATION_PC(VDI,"Virtual Desktop")
OFF_WORKSTATION_PC(JHST,"Jumphost")
OFF_APPLICATION_SERVER(Server,"Server/Service")

OFF_REVERSE_PROXY(zScalerC, "ZScaler Cloud")
OFF_REVERSE_PROXY(zScalerP, "ZScaler Private Access")
OFF_REVERSE_PROXY(zScalerI, "ZScaler Internet Access")
OFF_REVERSE_PROXY(PAM, "PAM")

KBAdmin -do-> KBendpoint : "using"
KBAdmin -do-> ForeignDevice : "BYOD"
3rdPartyAdmin -do-> ForeignDevice : "using"
3rdPartyAdmin -do-> KBendpoint : "using"

ForeignDevice -do-> VDI
VDI -do-> zScalerC
KBendpoint -do-> zScalerC
zScalerC -do-> zScalerP
zScalerC -do-> zScalerI
zScalerP -do-> PAM
KBendpoint ----do-> JHST : breakglass
JHST -do-> Server : breakglass
PAM -do-> Server


@enduml