@startuml
!include <office/all>
!include <azure/all>
!include <tupadr3/common>

OFF_ADMINISTRATOR(KBAdmin,"KB Admin")
OFF_ADMINISTRATOR(3rdPartyAdmin,"3rd Party Admin")

AzureActiveDirectory(EntraID,"EntraID","EntraID")

OFF_WORKSTATION_PC(KBendpoint,"KB Device")
OFF_WORKSTATION_PC(ForeignDevice,"non-KB Device")
OFF_WORKSTATION_PC(VDI,"Virtual Desktop")

frame zScaler {
    OFF_REVERSE_PROXY(zScalerC, "ZScaler Cloud")
    OFF_REVERSE_PROXY(zScalerI, "ZScaler Internet Access")
}

frame Kiwibank {
    OFF_REVERSE_PROXY(zScalerP, "ZScaler Private Access")
    OFF_REVERSE_PROXY(PAM, "PAM")
    OFF_WORKSTATION_PC(JHST,"Jumphost")
    OFF_APPLICATION_SERVER(Server,"Server/Service")
}

OFF_PUBLIC_CLOUD(SaaS,"Cloud Soln")

KBAdmin -do[#green,thickness=3]-> KBendpoint : "using"
KBAdmin -do-> ForeignDevice : "BYOD"
3rdPartyAdmin -do-> ForeignDevice : "using"
3rdPartyAdmin -do[#green,thickness=3]-> KBendpoint : "using"

ForeignDevice -do-> VDI
note left of VDI
    AVD, Remote Desktop???
end note

KBendpoint -[#blue,dashed]-> EntraID : "authN/Z"
VDI -[#blue,dashed]-> EntraID : "authN/Z"
zScalerC -[#blue,dashed]-> EntraID : "authN/Z"
zScalerP -[#blue,dashed]-> EntraID : "authN/Z"
PAM -[#blue,dashed]-> EntraID : "authN/Z"
SaaS -[#blue,dashed]-> EntraID : "authN/Z"


VDI -do[#green,thickness=3]-> zScalerC
KBendpoint -do[#green,thickness=3]-> zScalerC
zScalerC -do[#green,thickness=3]-> zScalerP
zScalerC -do[#green,thickness=3]-> zScalerI
zScalerI -[#green,thickness=3]> SaaS
zScalerP -do[#green,thickness=3]-> PAM
KBendpoint ----do[#red]-> JHST : <color:red>breakglass - usage by exception</color>
JHST -do[#red]-> Server : <color:red>breakglass  - usage by exception</color>
note left of JHST
    Jumphost use cases:
    1. Support site dark-start
    2. Support PAM restart
end note
PAM -do[#green,thickness=3]-> Server

@enduml
