@startuml
!include <awslib/all>
!include <azure/all>
!include <kubernetes/k8s-sprites-unlabeled-25pct>
!include <office/all>
!include <tupadr3/common>

actor customer
Mobileclient(phone,mobile,MOBILE)
Client(browser,browser,browser)
WAF(AKA_WAF,Akamai,WAF)


frame "Redshield" {
    frame "RED AWS" {
        WAF(RED_WAF,Redshield,WAF)
    }
    frame "RED NZ" {
        WAF(RED_F5,Redshield,F5)
    }
}

frame "KB AWS" {
SimpleStorageService(MDB_SPA_S3,"SPA Hosting Bucket",S3)
ElasticLoadBalancingApplicationLoadBalancer(SYD_ALB,ALB,SYD)
CloudFront(SPA_CF,"CloudFront",SPA)
CloudFront(API_CF,"CloudFront",API)
WAF(ALB_WAF,AWS,WAF)
    frame "CIP" {
        component "<$svc>\n\nistio" as istio
        component "<$pod>\n\nservice pod" as mservice
        AzureAPIManagement(APIM_D,"API GW","APIM")
    }
}

frame "NZ DC" {
    ElasticLoadBalancingApplicationLoadBalancer(F5,F5,NZDC)
    frame "IB" {
        OFF_APPLICATION_SERVER(IBs,"IB Servers")
    }
    frame "Middleware" {
        OFF_APPLICATION_SERVER(MWs,"Middleware Servers")
    }
}

"RED AWS" -- "NZ DC" : **Megaport**
"RED NZ" -- "NZ DC" : **Megaport**

customer -do-> browser
browser -do-> AKA_WAF : **Classic and MDB - Web and API**
browser -do-> SPA_CF : **SPA download**
AKA_WAF -do-> RED_WAF : **Classic**
AKA_WAF -do-> RED_F5 : **Classic**
RED_WAF -do-> F5
RED_F5 -do-> F5
F5 -do-> IBs
IBs-up-> F5
F5 -do-> MWs


customer -do-> phone
phone -do-> SPA_CF : **SPA download**
SPA_CF -do-> MDB_SPA_S3

phone -do-> AKA_WAF : **MDB API**
AKA_WAF -do-> API_CF : **MDB API**
API_CF -> ALB_WAF : **API**
ALB_WAF -do-> SYD_ALB : **API**
SYD_ALB -do-> istio
istio -do-> APIM_D
APIM_D -up-> istio
istio -do-> mservice

mservice -> F5 : **Calling Classic Services**

@enduml
