@startuml

== Classic Flow to NZ DC ==
customer -> browser
customer -> phone
browser -> Akamai_WAF : **Classic and MDB - Web and API**
browser -> SPA_CloudFront : **SPA download**
SPA_CloudFront ->o SPA_S3
Akamai_WAF -> RedShield_WAF : **Classic**
Akamai_WAF -> RedShield_F5 : **Classic**
RedShield_WAF -> F5 : Over Megaport
RedShield_F5 -> F5 : Over Megaport
F5 -> IB_Servers
IB_Servers -> F5
F5 ->o Middleware_Servers

== MDB SPA Download Flow ==

customer -> phone
phone -> SPA_CloudFront : **SPA download**
browser -> SPA_CloudFront : **SPA download**
SPA_CloudFront ->o SPA_S3
 
 == MDB API Flow ==

customer -> phone
phone -> Akamai_WAF : **MDB API**
Akamai_WAF -> API_CloudFront : **MDB API**
API_CloudFront -> CF_LoadBalancer_WAF : **API**
CF_LoadBalancer_WAF -> LoadBalancer : **API**
LoadBalancer -> istio
istio -> APIM_Data_Plane
APIM_Data_Plane -> istio
istio ->o Microservice


@enduml
