@startuml
package CSC_Global  [
    Registrar
    kiwibank.co.nz GLUE records
]

frame Akamai_EdgeDNS {
    database Akamai_Edge [
        external
        kiwibank.co.nz
    ]
}

frame Infoblox {
    database external_zones [
        external
        kiwibank.co.nz
    ]
    database internal_zones [
        internal
        kiwibank.co.nz
        bank.nzpfs.co.nz
        <color:red>kiwbank.internal</color>
    ]
}
cloud Internet

frame MSAD_DNS {
    database corp.bank.nzpfs.co.nz
    database dmz.kiwibank.co.nz
    database core.bank.nzpfs.co.nz
}

frame AWS_Route53 {
    frame "Root Account" {
        database aws.kiwibank.co.nz
    }
    frame "Network Account" {
        database prod.aws.kiwibank.co.nz
        database qa.aws.kiwibank.co.nz
        database test.aws.kiwibank.co.nz
        database dev.aws.kiwibank.co.nz
    }
    frame "Application Account" {
        database app.prod.aws.kiwibank.co.nz
        database app.qa.aws.kiwibank.co.nz
        database app.test.aws.kiwibank.co.nz
        database app.dev.aws.kiwibank.co.nz
    }
}

CSC_Global -do- Internet
Akamai_EdgeDNS -up- Internet

external_zones -up-> Akamai_Edge : **Zone XFER**
internal_zones -do-> corp.bank.nzpfs.co.nz : **delegation**
internal_zones -do-> core.bank.nzpfs.co.nz : **delegation**
internal_zones -do-> dmz.kiwibank.co.nz : **delegation**
internal_zones -do-> aws.kiwibank.co.nz : **delegation**

aws.kiwibank.co.nz -do-> prod.aws.kiwibank.co.nz : **delegation**
aws.kiwibank.co.nz -do-> qa.aws.kiwibank.co.nz : **delegation**
aws.kiwibank.co.nz -do-> test.aws.kiwibank.co.nz : **delegation**
aws.kiwibank.co.nz -do-> dev.aws.kiwibank.co.nz : **delegation**

prod.aws.kiwibank.co.nz -do-> app.prod.aws.kiwibank.co.nz : **delegation**
qa.aws.kiwibank.co.nz -do-> app.qa.aws.kiwibank.co.nz : **delegation**
test.aws.kiwibank.co.nz -do-> app.test.aws.kiwibank.co.nz : **delegation**
dev.aws.kiwibank.co.nz -do-> app.dev.aws.kiwibank.co.nz : **delegation**

@enduml