@startuml
package CSC_Global  [
    Registrar
    Kiwibank GLUE records
]

frame Akamai_EdgeDNS {
    database Akamai_Edge [
        external zones
    ]
}

frame Infoblox {
    database external_zones [
        external zones - hidden master
        kiwibank.co.nz
        kiwibank.app
        kiwibank.asia
        kiwibank.biz
        kiwibank.cards
        kiwibank.club
        kiwibank.cm
        kiwibank.co
        kiwibank.co.uk
        kiwibank.com
        kiwibank.digital
        kiwibank.kiwi
        kiwibank.limited
        kiwibank.net
        kiwibank.net.nz
        kiwibank.nz
        kiwibank.one
        kiwibank.online
    ]
    database internal_zones [
        internal
        kiwibank.co.nz
        <color:red>kiwbank.internal</color>
    ]
}

cloud Internet

frame MSAD_DNS {
    database corp.bank.nzpfs.co.nz
    database dmz.kiwibank.co.nz
    database core.bank.nzpfs.co.nz
    database bank.nzpfs.co.nz
    database network.nzpfs.co.nz
}

frame AWS_Route53 {
    frame "Root Account" {
        database aws.kiwibank.co.nz
    }
    frame "Network Account" {
        database prod.aws.kiwibank.co.nz
        database qa.aws.kiwibank.co.nz
        database test.aws.kiwibank.co.nz
        database dev.aws.kiwibank.co.nz
    }
    frame "Application Account" {
        database appname.prod.aws.kiwibank.co.nz
        database appname.qa.aws.kiwibank.co.nz
        database appname.test.aws.kiwibank.co.nz
        database appname.dev.aws.kiwibank.co.nz
    }
}

CSC_Global -do- Internet
Akamai_EdgeDNS -up- Internet

external_zones -up-> Akamai_Edge : **Zone XFER**
internal_zones -do-> bank.nzpfs.co.nz : **forwarding**
internal_zones -do-> network.nzpfs.co.nz : **forwarding**
bank.nzpfs.co.nz -do-> corp.bank.nzpfs.co.nz : **delegation**
bank.nzpfs.co.nz -do-> core.bank.nzpfs.co.nz : **delegation**
internal_zones -do-> dmz.kiwibank.co.nz : **delegation**
internal_zones -do-> aws.kiwibank.co.nz : **delegation**

aws.kiwibank.co.nz -do-> prod.aws.kiwibank.co.nz : **delegation**
aws.kiwibank.co.nz -do-> qa.aws.kiwibank.co.nz : **delegation**
aws.kiwibank.co.nz -do-> test.aws.kiwibank.co.nz : **delegation**
aws.kiwibank.co.nz -do-> dev.aws.kiwibank.co.nz : **delegation**

prod.aws.kiwibank.co.nz -do-> appname.prod.aws.kiwibank.co.nz : **delegation**
qa.aws.kiwibank.co.nz -do-> appname.qa.aws.kiwibank.co.nz : **delegation**
test.aws.kiwibank.co.nz -do-> appname.test.aws.kiwibank.co.nz : **delegation**
dev.aws.kiwibank.co.nz -do-> appname.dev.aws.kiwibank.co.nz : **delegation**

@enduml