@startuml
!include <office/all>
!include <tupadr3/common>


title NZ Datacentre Perimeter

cloud "Global Internet" {
    cloud "Cello Internet"
    cloud "Spark Internet"
    cloud "2 Degrees Internet"    
}

cloud "Megaport" {
    rectangle "MCR" as mcr
    rectangle "Redshield VXC" as redvxc
}

frame Redshield {
    rectangle "Redshield WAF" as redshield
}

frame AWS {
    rectangle "Sydney Transit Gateway" as sydtgw
}

frame NZDC {
    rectangle "External Switching" as extswt
    rectangle "RADWare" as RADware
    rectangle "ASR" as NZDC_ASR
    OFF_FIREWALL(NZDC_RCN,"RCN Firewall")
    OFF_FIREWALL(NZDC_TZ,"TZ Firewall")
    OFF_FIREWALL(NZDC_GRE,"GRE 1800F")
    OFF_FIREWALL(NZDC_BANKNET,"Banket Firewall")
    OFF_FIREWALL(NZDC_INT,"Internal Checkpoint")
    OFF_FIREWALL(NZDC_EXT,"External Checkpoint")
    rectangle "TZ Internal Switching" as NZDC_TZintswt
    rectangle "ACI Fabric" as aci

    extswt - NZDC_GRE
    extswt -down- NZDC_ASR
    extswt --down- NZDC_TZ
    extswt --down- NZDC_RCN
    extswt --down- NZDC_BANKNET
    extswt -down- RADware
    RADware - NZDC_GRE
    NZDC_ASR - RADware
    extswt -down-NZDC_EXT
    NZDC_EXT ---down- aci
    aci -down- NZDC_INT
    NZDC_TZ -down- aci
    NZDC_RCN -down- NZDC_TZintswt
    NZDC_TZintswt -down- aci
}

redshield -down- redvxc : "VXC"
redvxc -down- extswt
mcr -down- extswt : "VXC"
sydtgw -down- mcr : "DX"
"Spark Internet" -down- extswt : "Internet"
"Cello Internet" -down- extswt : "RCN Internet"
"2 Degrees Internet" -down- extswt : "Internet"



@enduml
