@startuml
!include <office/all>
!include <tupadr3/common>
!include <tupadr3/material/wifi>

cloud "Global Internet" {
    cloud "Cello Internet"    
}


frame Branch {
    OFF_ROUTER(BranchFW,"Firewall")
    OFF_SWITCH(BranchSW,"Switch")
    OFF_WORKSTATION("Workstation","Teller")
    MATERIAL_WIFI("AP","Wifi")
    BranchFW -- BranchSW
    BranchFW -- AP
    BranchSW -- Workstation
}

frame NZDC {
    OFF_SWITCH(DCFW,"RCN Firewall")
    OFF_SWITCH(TZFW,"Transit Zone Firewall")
    OFF_SWITCH(IntFW,"Internal Firewall")
    OFF_ACCESS_SERVICES(ZPA,"ZPA")
    OFF_ACCESS_SERVICES(ISE,"Cisco ISE")
    rectangle "Internal Network"
    DCFW -- IntFW
    IntFW -- "Internal Network"
    IntFW -up- TZFW
    "Internal Network" -do- ZPA
    "Internal Network" -do- ISE
}

frame "Critical SaaS" {
    OFF_3RD_PARTY_SERVICE(zScaler,"zScaler")
    note right of zScaler
        Access to ALL SaaS servies is via zScaler Internet Access
        Access to NZDC hosted resources via zScaler Private ACCESS (ZPA)
    end note
    OFF_3RD_PARTY_CALL_CENTER_SOLUTION(Genesys,"Genesys")
    OFF_PUBLIC_IM_CLOUD_SERVICE(MSTeams,"Teams")
    OFF_EMAIL_WORKLOAD(Exchange,"Exchange Online")
    OFF_3RD_PARTY_SERVICE(Teller,"Teller")
    OFF_3RD_PARTY_SERVICE(ServiceNow,"ServiceNow")
    zScaler -do- Genesys
    zScaler -do- MSTeams
    zScaler -do- Teller
    zScaler -do- ServiceNow
    zScaler -do- Exchange
}

frame "AWS AU" {
    OFF_SWITCH(TransitGW,"Transit Gateway")
    OFF_SWITCH(AWSGW,"AWS Egress Firewall")
    TransitGW - AWSGW
}

"Cello Internet" -- DCFW

TZFW -up- TransitGW : "Megaport Private Network"
TZFW -up- "Global Internet" : "Vocus & Spark"
"Cello Internet" -- BranchFW

AWSGW -do- "Global Internet"
"Critical SaaS" -do- "Global Internet"

note left of "Global Internet"
    If there is a NZ-based problem here CAN we route via NZ DC and AWS path?
    That is - 'egress' via AWS AU, and the AU peering.

    Manual failover/ reconfiguration timeframes are likely acceptable,
    but not timeframes that include design / trial and error.
    That is - we know how, and maybe have code to do. But to have
    BGP etc in place to automate MAY be a bit OTT.
end note

note left of "Cello Internet"
    The Cello Internet is ostensibly a 'private' network,
    composed of Cello customers. So entirely in Cello control,
    exposed to global internet via NZ peering partners.
end note

@enduml