@startuml
!include <office/all>
!include <tupadr3/common>


title "WAN - Current State"


cloud "Global Internet" {
    cloud "Spark Internet"
    cloud "2degrees Internet"
}

cloud "Megaport" {
    rectangle "AKL MCR" as aklmcr
    rectangle "SYD MCR" as sydmcr
    rectangle "MEL MCR" as melmcr
}

cloud "ACI Performance Hubs" {
    rectangle "SYD ACI PH" as sydph
    rectangle "MEL ACI PH" as melph
}

frame AWS_SYD_PROD {
    rectangle "Sydney Transit Gateway" as sydtgw
    rectangle "AWS SYD Fortigate" as sydfortigate
    sydtgw - sydfortigate
}
frame AWS_SYD_NONPROD {
    rectangle "Sydney Transit Gateway" as sydtgwnp
    rectangle "AWS SYD Fortigate" as sydfortigatenp
    sydtgwnp - sydfortigatenp
}

frame AZR_SYD {
    rectangle "Azure Sydney Access" as azrsydtgw
} 

frame Orbit {
    OFF_FIREWALL(ORB_TZ,"TZ Firewall")
    OFF_FIREWALL(ORB_INT,"Internal Firewall")
    OFF_ROUTER(ORB_WANRTR,"WAN Router")   
}
frame Kapua {
    OFF_FIREWALL(KAP_TZ,"TZ Firewall")
}

frame Abel {
    OFF_FIREWALL(ABL_TZ,"TZ Firewall")
    OFF_FIREWALL(ABL_INT,"Internal Firewall")
    OFF_ROUTER(ABL_WANRTR,"WAN Router")
}

"Spark Internet" -[#770077]- ABL_TZ
"2degrees Internet" -[#770077]- ORB_TZ
"2degrees Internet" -[#770077]- KAP_TZ

sydtgw -- aklmcr : DX
sydtgw -- sydmcr : DX
sydtgw -- melmcr : DX

azrsydtgw -- aklmcr : ER
azrsydtgw -- sydmcr : ER

sydmcr -up- sydph : VXC
melmcr -up- melph : VXC

 aklmcr -- ORB_WANRTR : VXC
 sydmcr -- ORB_WANRTR : VXC

 aklmcr -- ABL_WANRTR : VXC
 sydmcr -- ABL_WANRTR : VXC

ORB_WANRTR -- ORB_TZ
ABL_WANRTR -- ABL_TZ

ABL_TZ -- ABL_INT
ORB_TZ -- ORB_INT   

sydfortigate -- "Global Internet"
sydfortigatenp -- "Global Internet"

KAP_TZ .[#ff0000]. sydtgwnp : <color:red>"Internet VPN"</color>

ABL_TZ .[#ff0000]. sydtgw : <color:red>"Internet VPN"</color>
ABL_TZ .[#ff0000]. sydtgw : <color:red>"VPN over Megaport"</color>
ABL_TZ .[#ff0000]. azrsydtgw : <color:red>"Internet VPN"</color>
ABL_TZ .[#ff0000]. azrsydtgw : <color:red>"VPN over Megaport"</color>

ORB_TZ .[#ff0000]. sydtgw : <color:red>"Internet VPN"</color>
ORB_TZ .[#ff0000]. sydtgw : <color:red>"VPN over Megaport"</color>
ORB_TZ .[#ff0000]. azrsydtgw : <color:red>"Internet VPN"</color>
ORB_TZ .[#ff0000]. azrsydtgw : <color:red>"VPN over Megaport"</color>

sydtgw .[#ff0000]up. sydph : <color:red>"Internet VPN"</color>
sydtgw .[#ff0000]up. melph : <color:red>"Internet VPN"</color>

@enduml