@startuml
skinparam linetype ortho
!include <office/all>
!include <tupadr3/common>


title "WAN - Current State"


cloud "Global Internet" {
    cloud "2degrees Internet"
    cloud "Spark Internet"
}

cloud "Megaport" {
    rectangle "AKL MCR" as aklmcr
    rectangle "SYD MCR" as sydmcr
    rectangle "MEL MCR" as melmcr
}

cloud "ACI Performance Hubs" {
    rectangle "SYD ACI PH" as sydph
    rectangle "MEL ACI PH" as melph
}

frame AWS_SYD_PROD {
    rectangle "Sydney Transit Gateway" as sydtgw
    rectangle "AWS SYD Fortigate" as sydfortigate
    sydtgw - sydfortigate
}
frame AWS_SYD_NONPROD {
    rectangle "Sydney Transit Gateway" as sydtgwnp
}

frame AZR_SYD {
    rectangle "Azure Sydney Access" as azrsydtgw
} 

frame Orbit {
    OFF_FIREWALL(ORB_TZ,"TZ Firewall")
    OFF_FIREWALL(ORB_INT,"Internal Firewall")
    OFF_ROUTER(ORB_WANRTR,"WAN Router")
    OFF_SWITCH(ORB_LANSW,"LAN Switch")
    ORB_WANRTR - ORB_TZ
    ORB_TZ -down- ORB_INT
    ORB_INT -down-ORB_LANSW
}

frame Kapua {
    OFF_FIREWALL(KAP_TZ,"TZ Firewall")
    OFF_SWITCH(KAP_LANSW,"LAN Switch")
    KAP_TZ -down- KAP_LANSW
}

frame Abel {
    OFF_FIREWALL(ABL_TZ,"TZ Firewall")
    OFF_FIREWALL(ABL_INT,"Internal Firewall")
    OFF_ROUTER(ABL_WANRTR,"WAN Router")
    OFF_SWITCH(ABL_LANSW,"LAN Switch")
    ABL_WANRTR - ABL_TZ
    ABL_TZ -down- ABL_INT
    ABL_INT -down-ABL_LANSW
}

"2degrees Internet" -[#00ff00]- ORB_TZ
"2degrees Internet" -[#00ff00]- KAP_TZ
"Spark Internet" -[#00ff00]- ABL_TZ

ABL_LANSW - ORB_LANSW : <color:blue>"MACsec/MPLS"</color>
ABL_LANSW - KAP_LANSW : <color:blue>"MACsec/MPLS"</color>
ORB_LANSW - KAP_LANSW : <color:blue>"MACsec/MPLS"</color>

sydtgw -up[#0000ff]- aklmcr : DX
sydtgw -up[#0000ff]- sydmcr : DX
sydtgw -up[#0000ff]- melmcr : DX

azrsydtgw -up[#0000ff]- sydmcr : ER

sydmcr -up[#0000ff]- sydph : VXC
melmcr -up[#0000ff]- melph : VXC

 aklmcr -down[#0000ff]- ORB_WANRTR : VXC
 sydmcr -down[#0000ff]- ORB_WANRTR : VXC

 aklmcr -down[#0000ff]- ABL_WANRTR : VXC
 sydmcr -down[#0000ff]- ABL_WANRTR : VXC



sydfortigate -down[#00ff00]- "Global Internet"

KAP_TZ .[#ff0000]. sydtgwnp : <color:red>"Internet VPN"</color>

ABL_TZ .[#ff0000]. sydtgw : <color:red>"Internet VPN"</color>
ABL_TZ .[#ff0000]. sydtgw : <color:red>"VPN over Megaport"</color>
ABL_TZ .[#ff0000]. azrsydtgw : <color:red>"Internet VPN"</color>
ABL_TZ .[#ff0000]. azrsydtgw : <color:red>"VPN over Megaport"</color>

ORB_TZ .[#ff0000]. sydtgw : <color:red>"Internet VPN"</color>
ORB_TZ .[#ff0000]. sydtgw : <color:red>"VPN over Megaport"</color>
ORB_TZ .[#ff0000]. azrsydtgw : <color:red>"Internet VPN"</color>
ORB_TZ .[#ff0000]. azrsydtgw : <color:red>"VPN over Megaport"</color>

sydtgw .[#ff0000]. sydph : <color:red>"Internet VPN"</color>
sydtgw .[#ff0000]. melph : <color:red>"Internet VPN"</color>

@enduml