@startuml
!include <office/all>
!include <tupadr3/common>
!include <awslib/all>
!include <azure/all>


title "WAN - Reimagined"

frame AZR_SYD {
     AzureFirewall(azrsydfw,"Sydney Firewall",FW)
} 

frame AZR_AKL {
    AzureExpressRouteCircuit(azrakler,"Auckland ExpressRoute (Vocus - Albany)",ER)
    AzureFirewall(azraklfw,"Auckland Firewall",FW)
    }

frame Orbit {
    OFF_FIREWALL(ORB_RCN,"Retail Firewall")
    OFF_FIREWALL(ORB_TZ,"TZ Firewall")
    OFF_FIREWALL(ORB_BANKNET,"Banknet Firewall")
    OFF_FIREWALL(ORB_INT,"Internal Firewall")
    OFF_ROUTER(ORB_WANRTR,"WAN Router")   
    ORB_WANRTR -down- ORB_TZ
    ORB_BANKNET -down- ORB_TZ
    ORB_RCN -down- ORB_INT
    ORB_TZ -down- ORB_INT   
}

frame Kapua {
    OFF_ROUTER(KAP_WANRTR,"WAN Router")
}

frame Abel {
    OFF_FIREWALL(ABL_RCN,"Retail Firewall")
    OFF_FIREWALL(ABL_TZ,"TZ Firewall")
    OFF_FIREWALL(ABL_BANKNET,"Banknet Firewall")
    OFF_FIREWALL(ABL_INT,"Internal Firewall")
    OFF_ROUTER(ABL_WANRTR,"WAN Router")
    ABL_WANRTR -down- ABL_TZ
    ABL_BANKNET -down- ABL_TZ
    ABL_RCN -down- ABL_INT
    ABL_TZ -down- ABL_INT
}

AZR_SYD - AZR_AKL : vNet Peering

azrakler -down[#blue]- ORB_WANRTR : **ER**
azrakler -down[#blue]- ABL_WANRTR : **ER**


@enduml