@startuml
!include <awslib/all>
!include <office/all>
!include <tupadr3/common>

rectangle "<color:red>Red = New</color>" {

}

frame AWS {
    frame KB_LZ {
        rectangle VMware_Account #line:red;line.bold; {
            SimpleStorageService(S3Bucket,"Vmware Discovery Bucket",S3) #line:red;line.bold;
        } 
    }
    frame Datacom {
        OFF_CREDENTIALS(Datacom_User,"Datacom User")
    }
}

frame NZDC {
    OFF_REVERSE_PROXY(PRXY,"Outgoing Proxy")
    frame Ultracs {
        OFF_APPLICATION_SERVER(UL,"Ultracs")
        OFF_CREDENTIALS(ULU,"Ultracs User") #line:red;line.bold;
        note bottom of ULU 
                New user to enable reading Server information
                Requires sudo setup
            end note
    }
    
    frame VMware {
        OFF_APPLICATION_SERVER(DS,"AWS Discovery Server") #line:red;line.bold;
        note left of DS
            Firewall rules to allow Discovery Server to communicate with
            EVERY server in the environment
        end note
        frame vCentre {
            OFF_APPLICATION_SERVER(VC,"vCentre")
            OFF_CREDENTIALS(VCU,"vCentre User")  #line:red;line.bold;
            note bottom of VCU 
                New user to enable reading vCentre Inventory information
            end note
        }

        frame Linux {
            OFF_APPLICATION_SERVER(LX,"Linux Servers")
            OFF_CREDENTIALS(LXU,"Linux User") #line:red;line.bold;
            note bottom of LXU 
                New user to enable reading Server information
                Requires sudo setup
            end note
 
        } 
        
        frame Windows {
            OFF_APPLICATION_SERVER(WS,"Windows Servers")        
            OFF_CREDENTIALS(CORP_User,"CORP User") #line:red;line.bold;
            OFF_CREDENTIALS(CORE_User,"CORE User") #line:red;line.bold;
            OFF_CREDENTIALS(DMZ_User,"DMZ User") #line:red;line.bold;
            OFF_ACTIVE_DIRECTORY(CORP,"CORP")
            OFF_ACTIVE_DIRECTORY(CORE,"CORE")
            OFF_ACTIVE_DIRECTORY(DMZ,"DMZ")
            note bottom of WS
                New users with domain privileges to read system data
                using WinRM
            end note
        }
    }       
}

Datacom_User -[#red,thickness=3]> S3Bucket : "Read Access"
DS -up[#red,thickness=3]-> PRXY
PRXY -up[#red,thickness=3]-> S3Bucket : "Discovered Data Storage"
DS -do[#red,thickness=3]-> VCU : "Connect to vCentre"
DS -do[#red,thickness=3]-> LXU : "Connect to Linux Servers"
CORP_User -do- CORP
CORE_User -do- CORE
DMZ_User -do- DMZ
DS -do[#red,thickness=3]-> CORP_User : "Connect ot CORP Windows Servers"
DS -do[#red,thickness=3]-> CORE_User : "Connect ot CORE Windows Servers"
DS -do[#red,thickness=3]-> DMZ_User : "Connect ot DMZ Windows Servers"
DS -do[#red,thickness=3]-> ULU : "Connect to Ultracs"

@enduml
